package(default_visibility = ["//visibility:public"])

filegroup(
    name = "sample_models",
    srcs = [
        "sample_linear_model.json",
        "sample_model.xgb",
    ],
)

filegroup(
    name = "sample_config",
    srcs = ["config.json"],
)
